CREATE TABLE Z_EMPLEADO(
    CODIGO_EMPLEADO VARCHAR2(15) PRIMARY KEY,
    EMPLEADO_NOMBRE VARCHAR2(45) NOT NULL,
    EMPLEADO_APELLIDO VARCHAR2(45) NOT NULL,
    EMPLEADO_DIRECCION VARCHAR2(45) NOT NULL,
    EMPLEADO_TELEFONO VARCHAR2(9) NOT NULL,
    EMPLEADO_CORREO VARCHAR2(45) NOT NULL,
    EMPLEADO_FECHANACIMIENTO DATE NOT NULL,
    EMPLEADO_DNI VARCHAR2(8) NOT NULL,
    EMPLEADO_SUELDO NUMBER(6,2) NULL
);

CREATE TABLE Z_ADMINISTRADOR(
    CODIGO_ADMINISTRADOR VARCHAR2(15),
    CONSTRAINT FK_EMP_AD FOREIGN KEY (CODIGO_ADMINISTRADOR) REFERENCES Z_EMPLEADO(CODIGO_EMPLEADO),
    CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (CODIGO_ADMINISTRADOR)
);

CREATE TABLE Z_VENDEDOR(
    CODIGO_VENDEDOR VARCHAR2(15),
    CONSTRAINT FK_EMP_VEN FOREIGN KEY (CODIGO_VENDEDOR) REFERENCES Z_EMPLEADO(CODIGO_EMPLEADO),
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (CODIGO_VENDEDOR)
);

CREATE TABLE Z_ALMACENERO(
    CODIGO_ALMACENERO VARCHAR2(15),
    CONSTRAINT FK_EMP_ALM FOREIGN KEY (CODIGO_ALMACENERO) REFERENCES Z_EMPLEADO(CODIGO_EMPLEADO),
    CONSTRAINT PK_ALMACENERO PRIMARY KEY (CODIGO_ALMACENERO)
);

CREATE TABLE Z_USUARIO_EMPLEADO(
    CODIGO_EMPLEADO VARCHAR2(15),
    USUARIO_CONTRASEÑA VARCHAR2(45),
    CONSTRAINT FK_U_E FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES Z_EMPLEADO(CODIGO_EMPLEADO),
    CONSTRAINT PK_USU_EMP PRIMARY KEY (CODIGO_EMPLEADO)
);

CREATE TABLE Z_TIPO_OPERARIO(
    CODIGO_TIPO_OPERARIO INT PRIMARY KEY,
    NOMBRE_TIPO_OPERARIO VARCHAR2(45) NOT NULL,
    DESCRIPCION_TIPO_OPERARIO VARCHAR2(45) NOT NULL
);

CREATE TABLE Z_OPERARIO(
    CODIGO_OPERARIO VARCHAR2(15),
    TIPO_OPERARIO INTEGER,
    CONSTRAINT FK_EM_OP FOREIGN KEY (CODIGO_OPERARIO) REFERENCES Z_EMPLEADO(CODIGO_EMPLEADO),
    CONSTRAINT FK_OP_TOP FOREIGN KEY (TIPO_OPERARIO) REFERENCES Z_TIPO_OPERARIO(CODIGO_TIPO_OPERARIO),
    CONSTRAINT PK_OPERARIO PRIMARY KEY (CODIGO_OPERARIO)
);

CREATE TABLE Z_PRODUCTO(
   CODIGO_PRODUCTO VARCHAR2(15) PRIMARY KEY,
   NOMBRE_PRODUCTO VARCHAR2(45) NOT NULL,
   COLOR_PRODUCTO VARCHAR2(45) NOT NULL,
   PRECIO_CORTADO NUMBER(4,2) NOT NULL,
   PRECIO_APARADO NUMBER(4,2) NOT NULL,
   PRECIO_ARMADO NUMBER(4,2) NOT NULL,
   PRECIO_ACABADO NUMBER(4,2) NOT NULL,
   PRECIO_VENTA NUMBER(5,2) NOT NULL
);

CREATE TABLE Z_PRODUCCION(
    CODIGO_ORDEN VARCHAR2(15),
    CODIGO_OPERARIO VARCHAR2(15),
    CODIGO_PRODUCTO VARCHAR2(15),
    CANTIDAD_PRODUCIDA NUMBER(5,2) NOT NULL,
    TOTAL_PAGAR NUMBER(6,2) NOT NULL,
    FECHA_ORDEN VARCHAR2(10),
    ESTADO_ORDEN INT,
    CONSTRAINT FK_PRO_OP FOREIGN KEY (CODIGO_OPERARIO) REFERENCES Z_OPERARIO(CODIGO_OPERARIO),
    CONSTRAINT FK_PRO_PRO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES Z_PRODUCTO(CODIGO_PRODUCTO),
    CONSTRAINT PK_PRODUCCION PRIMARY KEY (CODIGO_OPERARIO,CODIGO_PRODUCTO)
);

CREATE TABLE Z_CATEGORIA_INSUMO(
    CODIGO_CAT_INSUMO VARCHAR2(15) PRIMARY KEY,
    NOMBRE_CAT_INSUMO VARCHAR2(45) NOT NULL,
    DESCRIPCION_CAT_INSUMO VARCHAR2(45) NOT NULL
);

CREATE TABLE Z_INSUMO(
    CODIGO_INSUMO VARCHAR2(15) PRIMARY KEY,
    NOMBRE_INSUMO VARCHAR2(45) NOT NULL,
    CATEGORIA_INSUMO VARCHAR2(15),
    CONSTRAINT FK_IN_CAT_IN FOREIGN KEY (CATEGORIA_INSUMO) REFERENCES Z_CATEGORIA_INSUMO(CODIGO_CAT_INSUMO)
);

CREATE TABLE Z_ALMACEN(
    CODIGO_ALMACEN VARCHAR2(15) PRIMARY KEY,
    NOMBRE_ALMACEN VARCHAR2(45) NOT NULL
);

CREATE TABLE Z_INSUMO_HAS_ALMACEN(
    CODIGO_INSUMO VARCHAR2(15),
    CODIGO_ALMACEN VARCHAR2(15),
    CANTIDAD_INSUMO INT,
    CONSTRAINT FK_IHA_IN FOREIGN KEY (CODIGO_INSUMO) REFERENCES Z_INSUMO(CODIGO_INSUMO),
    CONSTRAINT FK_IHA_AL FOREIGN KEY (CODIGO_ALMACEN) REFERENCES Z_ALMACEN(CODIGO_ALMACEN),
    CONSTRAINT PK_INSU_HA_AL PRIMARY KEY (CODIGO_INSUMO,CODIGO_ALMACEN)
);

CREATE TABLE Z_PRODUCTO_HAS_ALMACEN(
    CODIGO_PRODUCTO VARCHAR2(15),
    CODIGO_ALMACEN VARCHAR2(15),
    CANTIDAD_PRODUCTO INT,
    CONSTRAINT FK_PHA_IN FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES Z_PRODUCTO(CODIGO_PRODUCTO),
    CONSTRAINT FK_PHA_AL FOREIGN KEY (CODIGO_ALMACEN) REFERENCES Z_ALMACEN(CODIGO_ALMACEN),
    CONSTRAINT PK_PRO_HA_AL PRIMARY KEY (CODIGO_PRODUCTO,CODIGO_ALMACEN)
);

CREATE TABLE Z_TIPO_DOCUMENTO(
    CODIGO_TIPO_DOCUMENTO VARCHAR2(15) PRIMARY KEY,
    DESCRIPCION_TIPO_DOCUMENTO VARCHAR2(45) NOT NULL,
    CANTIDAD_DIGITOS VARCHAR2(45) NOT NULL
);

CREATE TABLE Z_CLIENTE(
    CODIGO_CLIENTE VARCHAR2(15) PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR2(45) NOT NULL,
    APELIIDO_CLIENTE VARCHAR2(45) NOT NULL,
    CODIGO_TIPO_DOCUMENTO VARCHAR2(15) NOT NULL,
    NDOCUMENTO_CLIENTE VARCHAR2(45) NOT NULL,
    TELEFONO_CLIENTE VARCHAR2(9) NOT NULL,
    DIRECCION_CLIENTE VARCHAR2(45) NOT NULL,
    CORREO_CLIENTE VARCHAR2(45) NOT NULL
);

CREATE TABLE Z_USUARIO_CLIENTE(
    CODIGO_CLIENTE VARCHAR2(15),
    USUARIO_CONTRASEÑA VARCHAR2(45),
    CONSTRAINT FK_UC_CL FOREIGN KEY (CODIGO_CLIENTE) REFERENCES Z_CLIENTE(CODIGO_CLIENTE),
    CONSTRAINT PK_US_CL PRIMARY KEY (CODIGO_CLIENTE)
);

CREATE TABLE Z_TIPO_COMPROBANTE(
    CODIGO_TIPO_COMPROBANTE VARCHAR2(15) PRIMARY KEY,
    NOMBRE_TIPO_COMPROBANTE VARCHAR2(45) NOT NULL
);

CREATE TABLE Z_VENTA(
    CODIGO_VENTA VARCHAR2(15) UNIQUE,
    CODIGO_CLIENTE VARCHAR2(15),
    CODIGO_VENDEDOR VARCHAR2(15),
    FECHA_VENTA DATE NOT NULL,
    DIRECCION_VENTA VARCHAR2(45) NULL,
    CONSTRAINT FK_V_C FOREIGN KEY (CODIGO_CLIENTE) REFERENCES Z_CLIENTE(CODIGO_CLIENTE),
    CONSTRAINT FK_V_V FOREIGN KEY (CODIGO_VENDEDOR) REFERENCES Z_VENDEDOR(CODIGO_VENDEDOR),
    CONSTRAINT PK_VENTA PRIMARY KEY (CODIGO_VENTA,CODIGO_CLIENTE,CODIGO_VENDEDOR)
);

CREATE TABLE Z_COMPROBANTE(
    CODIGO_COMPROBANTE VARCHAR2(15),
    CODIGO_PRODUCTO VARCHAR2(15),
    CODIGO_VENTA VARCHAR2(15),
    CODIGO_TIPO_COMPROBANTE VARCHAR2(15),
    TOTAL_PAGAR NUMBER(7,2),
    FECHA_PAGO DATE,
    ESTADO_COMPROBANTE INTEGER NOT NULL,
    TIPOPAGO VARCHAR2(45) NOT NULL,
    CONSTRAINT FK_C_P FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES Z_PRODUCTO(CODIGO_PRODUCTO),
    CONSTRAINT FK_C_V FOREIGN KEY (CODIGO_VENTA) REFERENCES Z_VENTA(CODIGO_VENTA),
    CONSTRAINT PK_COMPROBANTE PRIMARY KEY (CODIGO_COMPROBANTE,CODIGO_PRODUCTO,CODIGO_VENTA)
);



































